### PR TITLE
Fix TR deprecation warnings

### LINKED ISSUE #261: Dealing with deprecations in TR
When I build my project with TR enabled I got warnings like this one:
```
[warn] .../TR.scala:1587: method getColor in class Resources is deprecated: see corresponding Javadoc for more information.
[warn]         c.getResources.getColor(resid)
[warn]              
```
(same for `c.getResources.getDrawable(resid)`).

I would be happy to build with `-Xfatal-warnings` and this is the last issue that separates me currently from warning-free build.

If there is no way of suppressing those, that I am unaware of, would it be a problem to add one?

### PR DESCRIPTION
**Pull request by Taig**
Gets rid off deprecations warnings by forwarding deprecated calls as discussed in https://issues.scala-lang.org/browse/SI-7934

Fixes #261

### CODE REVIEW

**Comment by pfn** [comment]
Unfortunately, builds will fail if you have platformTarget lower than android-23 and/or android-21.

This is the whole reason behind the difference in TR generation being done in code, rather than entirely within the template

**Comment by Taig** [comment]
Oh, obviously. Good catch, thanks!

**Comment by pfn** [comment]
There's actually a lot of these issues that need to be fixed in TR  :( (basically any compile target under like 14 will fail  :()

File: src/resources.scala [hunk 1]
```diff
@@ -405,20 +405,46 @@ object Resources {
                |  }""".stripMargin :: acc
           }
 
+          val deprForward = {
+            if (platformApi < 21) ""
+            else {
+              val color =
+                """
+                  |    def getColor(c: Context, resid: Int): Int = {
```
Comment (pfn) [inline src/resources.scala]: `@inline`

File: src/resources.scala [hunk 2]
```diff
@@ -405,20 +405,46 @@ object Resources {
...
+                  |      if (Build.VERSION.SDK_INT >= 23)
+                  |        c.getColor(resid)
+                  |      else
+                  |        c.getResources.getColor(resid)
+                  |    }""".stripMargin
+              val drawable =
+               """
+                  |    def getDrawable(c: Context, resid: Int): Drawable = {
```
Comment (pfn) [inline src/resources.scala]: `@inline`

**Comment by pfn** [comment]
Just fix the `@inline` annotations, and this is good to go. Thanks

File: src/resources.scala (hunk 1 above)
Comment (pfn) [inline src/resources.scala]: Also, `@TargetApi(23)`

File: src/resources.scala (hunk 2 above)
Comment (pfn) [inline src/resources.scala]: `@TargetApi(21)`
